#![no_std]
use soroban_sdk::{
    contract, contracterror, contractimpl, contracttype,
    token, Address, Env, String, symbol_short,
};

// ─────────────────────────────────────────────────────────────────────────────
// TTL constants
// ~1 ledger per 5 seconds on Stellar mainnet
// ─────────────────────────────────────────────────────────────────────────────
const LEDGER_TTL_THRESHOLD: u32 = 518_400;   // ~30 days
const LEDGER_TTL_EXTEND_TO: u32 = 1_036_800; // ~60 days
const PAYLINK_TTL_THRESHOLD: u32 = 103_680;  // ~6 days
const PAYLINK_TTL_EXTEND_TO: u32 = 207_360;  // ~12 days

// ─────────────────────────────────────────────────────────────────────────────
// Errors
// ─────────────────────────────────────────────────────────────────────────────
#[contracterror]
#[derive(Clone, Debug, PartialEq)]
pub enum Error {
    AlreadyInitialized    = 1,
    NotInitialized        = 2,
    ContractPaused        = 3,
    Unauthorized          = 4,
    InsufficientBalance   = 5,
    InvalidAmount         = 6,
    PayLinkNotFound       = 7,
    PayLinkAlreadyPaid    = 8,
    PayLinkCancelled      = 9,
    PayLinkAlreadyExists  = 10,
    PayLinkExpired        = 11,
    NotPayLinkCreator     = 12,
    FeeTooHigh            = 13,
    UsernameTaken         = 14,
    UsernameNotFound      = 15,
    UserAlreadyRegistered = 16,
    UserNotFound          = 17,
}

// ─────────────────────────────────────────────────────────────────────────────
// Storage keys
// ─────────────────────────────────────────────────────────────────────────────
#[derive(Clone)]
#[contracttype]
pub enum DataKey {
    // Instance (global config)
    Admin,
    UsdcToken,
    FeeRateBps,
    FeeTreasury,
    Paused,

    // Persistent (per-user)
    Balance(String),            // username  → i128 balance
    UsernameToAddr(String),     // username  → Address  (forward lookup)
    AddrToUsername(Address),    // Address   → username (reverse lookup)

    // Persistent (per-paylink)
    PayLink(String),            // token_id  → PayLinkData
}

// ─────────────────────────────────────────────────────────────────────────────
// PayLink
// ─────────────────────────────────────────────────────────────────────────────
#[derive(Clone)]
#[contracttype]
pub struct PayLinkData {
    pub creator_username:  String,
    pub amount:            i128,
    pub note:              String,
    pub paid:              bool,
    pub cancelled:         bool,
    pub expiration_ledger: u32,
}

// ─────────────────────────────────────────────────────────────────────────────
// Contract
// ─────────────────────────────────────────────────────────────────────────────
#[contract]
pub struct CheesePay;

#[contractimpl]
impl CheesePay {

    // ─────────────────────────────────────────────────────────────────────────
    // INIT
    // ─────────────────────────────────────────────────────────────────────────

    pub fn initialize(
        env:          Env,
        admin:        Address,
        usdc_token:   Address,
        fee_rate_bps: i128,
        fee_treasury: Address,
    ) -> Result<(), Error> {
        if env.storage().instance().has(&DataKey::Admin) {
            return Err(Error::AlreadyInitialized);
        }
        if fee_rate_bps < 0 || fee_rate_bps > 500 {
            return Err(Error::FeeTooHigh);
        }
        env.storage().instance().set(&DataKey::Admin,       &admin);
        env.storage().instance().set(&DataKey::UsdcToken,   &usdc_token);
        env.storage().instance().set(&DataKey::FeeRateBps,  &fee_rate_bps);
        env.storage().instance().set(&DataKey::FeeTreasury, &fee_treasury);
        env.storage().instance().set(&DataKey::Paused,      &false);
        Ok(())
    }

    // ─────────────────────────────────────────────────────────────────────────
    // USER REGISTRATION
    // Called by Cheese backend when a user completes signup.
    // Links their username to their Stellar address (generated by Cheese).
    // ─────────────────────────────────────────────────────────────────────────

    /// Register a new Cheese user. Admin only.
    ///
    /// `address` is the Stellar address Cheese generated and holds the
    /// secret key for — the user never sees this key.
    /// `username` is their @handle (e.g. "temi").
    pub fn register_user(
        env:      Env,
        username: String,
        address:  Address,
    ) -> Result<(), Error> {
        Self::require_admin(&env)?;

        // Username must be unique
        let u_key = DataKey::UsernameToAddr(username.clone());
        if env.storage().persistent().has(&u_key) {
            return Err(Error::UsernameTaken);
        }

        // Address must not already have a username
        let a_key = DataKey::AddrToUsername(address.clone());
        if env.storage().persistent().has(&a_key) {
            return Err(Error::UserAlreadyRegistered);
        }

        // Write both directions of the mapping
        env.storage().persistent().set(&u_key, &address);
        env.storage().persistent().set(&a_key, &username);
        Self::extend_ttl_persistent(&env, &u_key);
        Self::extend_ttl_persistent(&env, &a_key);

        // Initialise balance at zero explicitly
        let b_key = DataKey::Balance(username.clone());
        env.storage().persistent().set(&b_key, &0_i128);
        Self::extend_ttl_persistent(&env, &b_key);

        env.events().publish(
            (symbol_short!("reg_user"), username.clone()),
            address,
        );

        Ok(())
    }

    // ─────────────────────────────────────────────────────────────────────────
    // DEPOSIT
    // Called by Cheese backend when a user adds funds.
    // The USDC is already in the contract's Stellar account (deposited via
    // a direct Stellar payment to the contract address from the user's
    // external wallet) — this function just credits the internal balance.
    //
    // Why no token.transfer() here?
    // For a custodial wallet the deposit flow is:
    //   1. User sends USDC to Cheese's contract address from any wallet
    //   2. Cheese backend detects the incoming payment via Horizon streaming
    //   3. Cheese backend calls deposit() to credit the user's internal balance
    //
    // This is simpler, cheaper, and does not require the user to interact
    // with Soroban at all — they just do a standard USDC payment.
    // ─────────────────────────────────────────────────────────────────────────

    pub fn deposit(
        env:      Env,
        username: String,
        amount:   i128,
    ) -> Result<(), Error> {
        Self::require_admin(&env)?;
        Self::require_not_paused(&env)?;

        if amount <= 0 {
            return Err(Error::InvalidAmount);
        }

        // Ensure user exists
        Self::require_user_exists(&env, &username)?;

        let key     = DataKey::Balance(username.clone());
        let current = Self::read_balance(&env, &key);
        Self::write_balance(&env, &key, current + amount);

        env.events().publish(
            (symbol_short!("deposit"), username.clone()),
            amount,
        );

        Ok(())
    }

    // ─────────────────────────────────────────────────────────────────────────
    // WITHDRAW
    // Called by Cheese backend after user requests a withdrawal.
    // Backend verifies user PIN, then:
    //   1. Calls withdraw() to debit internal balance
    //   2. Separately sends the actual USDC payment from contract address
    //      to the user's destination wallet via Stellar SDK
    // ─────────────────────────────────────────────────────────────────────────

    pub fn withdraw(
        env:        Env,
        username:   String,
        amount:     i128,
        // destination is recorded in the event for the backend
        // to use when constructing the outbound Stellar payment
        to_address: Address,
    ) -> Result<(), Error> {
        Self::require_admin(&env)?;
        Self::require_not_paused(&env)?;

        if amount <= 0 {
            return Err(Error::InvalidAmount);
        }

        let key     = DataKey::Balance(username.clone());
        let balance = Self::read_balance(&env, &key);

        if balance < amount {
            return Err(Error::InsufficientBalance);
        }

        Self::write_balance(&env, &key, balance - amount);

        env.events().publish(
            (symbol_short!("withdraw"), username.clone()),
            (amount, to_address),
        );

        Ok(())
    }

    // ─────────────────────────────────────────────────────────────────────────
    // TRANSFER (username → username)
    // This is the core Cheese P2P flow.
    // Backend verifies user PIN/biometric, then calls this as admin.
    // ─────────────────────────────────────────────────────────────────────────

    pub fn transfer(
        env:           Env,
        from_username: String,
        to_username:   String,
        amount:        i128,
    ) -> Result<(), Error> {
        Self::require_admin(&env)?;
        Self::require_not_paused(&env)?;

        if amount <= 0 {
            return Err(Error::InvalidAmount);
        }

        // Both users must be registered
        Self::require_user_exists(&env, &from_username)?;
        Self::require_user_exists(&env, &to_username)?;

        let fee_bps: i128 = env.storage().instance()
            .get(&DataKey::FeeRateBps).unwrap_or(0);
        let fee = (amount * fee_bps) / 10_000;
        let net = amount - fee;

        // Debit sender
        let from_key = DataKey::Balance(from_username.clone());
        let from_bal = Self::read_balance(&env, &from_key);
        if from_bal < amount {
            return Err(Error::InsufficientBalance);
        }
        Self::write_balance(&env, &from_key, from_bal - amount);

        // Credit recipient
        let to_key = DataKey::Balance(to_username.clone());
        let to_bal = Self::read_balance(&env, &to_key);
        Self::write_balance(&env, &to_key, to_bal + net);

        // Credit fee to treasury internal balance
        // (treasury is also a registered user, or handled separately)
        if fee > 0 {
            let treasury: Address = env.storage().instance()
                .get(&DataKey::FeeTreasury)
                .ok_or(Error::NotInitialized)?;
            let usdc = Self::usdc_client(&env);
            usdc.transfer(
                &env.current_contract_address(),
                &treasury,
                &fee,
            );
        }

        env.events().publish(
            (symbol_short!("transfer"), from_username.clone(), to_username.clone()),
            (amount, fee),
        );

        Ok(())
    }

    // ─────────────────────────────────────────────────────────────────────────
    // PAYLINK
    // ─────────────────────────────────────────────────────────────────────────

    pub fn create_paylink(
        env:               Env,
        creator_username:  String,
        token_id:          String,
        amount:            i128,
        note:              String,
        expiration_ledger: u32,
    ) -> Result<(), Error> {
        Self::require_admin(&env)?;
        Self::require_not_paused(&env)?;

        if amount <= 0 {
            return Err(Error::InvalidAmount);
        }

        Self::require_user_exists(&env, &creator_username)?;

        let key = DataKey::PayLink(token_id.clone());
        if env.storage().persistent().has(&key) {
            return Err(Error::PayLinkAlreadyExists);
        }

        if expiration_ledger <= env.ledger().sequence() {
            return Err(Error::PayLinkExpired);
        }

        let link = PayLinkData {
            creator_username: creator_username.clone(),
            amount,
            note,
            paid:             false,
            cancelled:        false,
            expiration_ledger,
        };

        env.storage().persistent().set(&key, &link);
        env.storage().persistent().extend_ttl(
            &key,
            PAYLINK_TTL_THRESHOLD,
            PAYLINK_TTL_EXTEND_TO,
        );

        env.events().publish(
            (symbol_short!("pl_create"), creator_username),
            (token_id, amount),
        );

        Ok(())
    }

    /// Pay a PayLink by username.
    /// Payer can be anonymous (not a Cheese user) if paying from external
    /// wallet — but for internal settlement, payer_username must be registered.
    pub fn pay_paylink(
        env:           Env,
        payer_username: String,
        token_id:       String,
    ) -> Result<(), Error> {
        Self::require_admin(&env)?;
        Self::require_not_paused(&env)?;

        Self::require_user_exists(&env, &payer_username)?;

        let key  = DataKey::PayLink(token_id.clone());
        let mut link: PayLinkData = env.storage().persistent()
            .get(&key)
            .ok_or(Error::PayLinkNotFound)?;

        if link.paid {
            return Err(Error::PayLinkAlreadyPaid);
        }
        if link.cancelled {
            return Err(Error::PayLinkCancelled);
        }
        if env.ledger().sequence() > link.expiration_ledger {
            return Err(Error::PayLinkExpired);
        }

        let fee_bps: i128 = env.storage().instance()
            .get(&DataKey::FeeRateBps).unwrap_or(0);
        let fee = (link.amount * fee_bps) / 10_000;
        let net = link.amount - fee;

        // Debit payer
        let payer_key = DataKey::Balance(payer_username.clone());
        let payer_bal = Self::read_balance(&env, &payer_key);
        if payer_bal < link.amount {
            return Err(Error::InsufficientBalance);
        }
        Self::write_balance(&env, &payer_key, payer_bal - link.amount);

        // Credit creator
        let creator_key = DataKey::Balance(link.creator_username.clone());
        let creator_bal = Self::read_balance(&env, &creator_key);
        Self::write_balance(&env, &creator_key, creator_bal + net);

        // Fee to treasury
        if fee > 0 {
            let treasury: Address = env.storage().instance()
                .get(&DataKey::FeeTreasury)
                .ok_or(Error::NotInitialized)?;
            let usdc = Self::usdc_client(&env);
            usdc.transfer(
                &env.current_contract_address(),
                &treasury,
                &fee,
            );
        }

        link.paid = true;
        env.storage().persistent().set(&key, &link);

        env.events().publish(
            (symbol_short!("pl_paid"), payer_username, link.creator_username.clone()),
            (token_id, link.amount, fee),
        );

        Ok(())
    }

    pub fn cancel_paylink(
        env:             Env,
        creator_username: String,
        token_id:         String,
    ) -> Result<(), Error> {
        Self::require_admin(&env)?;

        let key  = DataKey::PayLink(token_id.clone());
        let mut link: PayLinkData = env.storage().persistent()
            .get(&key)
            .ok_or(Error::PayLinkNotFound)?;

        if link.creator_username != creator_username {
            return Err(Error::NotPayLinkCreator);
        }
        if link.paid {
            return Err(Error::PayLinkAlreadyPaid);
        }
        if link.cancelled {
            return Err(Error::PayLinkCancelled);
        }

        link.cancelled = true;
        env.storage().persistent().set(&key, &link);

        env.events().publish(
            (symbol_short!("pl_cancel"), creator_username),
            token_id,
        );

        Ok(())
    }

    // ─────────────────────────────────────────────────────────────────────────
    // VIEW FUNCTIONS
    // ─────────────────────────────────────────────────────────────────────────

    pub fn balance(env: Env, username: String) -> i128 {
        Self::read_balance(&env, &DataKey::Balance(username))
    }

    pub fn resolve_username(env: Env, username: String) -> Result<Address, Error> {
        env.storage().persistent()
            .get(&DataKey::UsernameToAddr(username))
            .ok_or(Error::UsernameNotFound)
    }

    pub fn get_username(env: Env, address: Address) -> Result<String, Error> {
        env.storage().persistent()
            .get(&DataKey::AddrToUsername(address))
            .ok_or(Error::UserNotFound)
    }

    pub fn get_paylink(env: Env, token_id: String) -> Result<PayLinkData, Error> {
        env.storage().persistent()
            .get(&DataKey::PayLink(token_id))
            .ok_or(Error::PayLinkNotFound)
    }

    pub fn fee_rate(env: Env) -> i128 {
        env.storage().instance()
            .get(&DataKey::FeeRateBps).unwrap_or(0)
    }

    pub fn is_paused(env: Env) -> bool {
        env.storage().instance()
            .get(&DataKey::Paused).unwrap_or(false)
    }

    // ─────────────────────────────────────────────────────────────────────────
    // ADMIN
    // ─────────────────────────────────────────────────────────────────────────

    pub fn set_fee_rate(env: Env, new_fee_bps: i128) -> Result<(), Error> {
        Self::require_admin(&env)?;
        if new_fee_bps < 0 || new_fee_bps > 500 {
            return Err(Error::FeeTooHigh);
        }
        env.storage().instance().set(&DataKey::FeeRateBps, &new_fee_bps);
        env.events().publish((symbol_short!("fee_set"),), new_fee_bps);
        Ok(())
    }

    pub fn set_fee_treasury(env: Env, new_treasury: Address) -> Result<(), Error> {
        Self::require_admin(&env)?;
        env.storage().instance().set(&DataKey::FeeTreasury, &new_treasury);
        Ok(())
    }

    pub fn transfer_admin(env: Env, new_admin: Address) -> Result<(), Error> {
        Self::require_admin(&env)?;
        env.storage().instance().set(&DataKey::Admin, &new_admin);
        env.events().publish((symbol_short!("adm_xfer"),), new_admin);
        Ok(())
    }

    pub fn pause(env: Env) -> Result<(), Error> {
        Self::require_admin(&env)?;
        env.storage().instance().set(&DataKey::Paused, &true);
        env.events().publish((symbol_short!("paused"),), ());
        Ok(())
    }

    pub fn unpause(env: Env) -> Result<(), Error> {
        Self::require_admin(&env)?;
        env.storage().instance().set(&DataKey::Paused, &false);
        env.events().publish((symbol_short!("unpaused"),), ());
        Ok(())
    }

    // ─────────────────────────────────────────────────────────────────────────
    // PRIVATE HELPERS
    // ─────────────────────────────────────────────────────────────────────────

    fn require_not_paused(env: &Env) -> Result<(), Error> {
        let paused: bool = env.storage().instance()
            .get(&DataKey::Paused).unwrap_or(false);
        if paused { Err(Error::ContractPaused) } else { Ok(()) }
    }

    fn require_admin(env: &Env) -> Result<(), Error> {
        let admin: Address = env.storage().instance()
            .get(&DataKey::Admin)
            .ok_or(Error::NotInitialized)?;
        admin.require_auth();
        Ok(())
    }

    fn require_user_exists(env: &Env, username: &String) -> Result<(), Error> {
        if !env.storage().persistent()
            .has(&DataKey::UsernameToAddr(username.clone()))
        {
            return Err(Error::UsernameNotFound);
        }
        Ok(())
    }

    fn usdc_client(env: &Env) -> token::TokenClient {
        let addr: Address = env.storage().instance()
            .get(&DataKey::UsdcToken).unwrap();
        token::TokenClient::new(env, &addr)
    }

    fn read_balance(env: &Env, key: &DataKey) -> i128 {
        let balance: i128 = env.storage().persistent()
            .get(key).unwrap_or(0);
        if balance > 0 {
            Self::extend_ttl_persistent(env, key);
        }
        balance
    }

    fn write_balance(env: &Env, key: &DataKey, amount: i128) {
        env.storage().persistent().set(key, &amount);
        Self::extend_ttl_persistent(env, key);
    }

    fn extend_ttl_persistent(env: &Env, key: &DataKey) {
        env.storage().persistent().extend_ttl(
            key,
            LEDGER_TTL_THRESHOLD,
            LEDGER_TTL_EXTEND_TO,
        );
    }
}